config/routes.rb
Rails.application.routes.draw do
  
  controller :community do
    get 'community', to: 'community#index'
    post 'community/search', to: 'community#search'
    get 'community/last_week', to: 'community#last_week', as: :last_week_community
    get 'community/:plz', to: 'community#show', as: :show_community
  end
  
  resources :taggings
  
  resources :tags do
    member do
      put :add
      put :orphanize
    end
  end
  
  resources :posts
  
  resources :participations do
    member do
      get :activate
    end
  end
  
  resources :streams do
    resources :participations
    resources :posts
  end
  
  resources :orderquants
  
  resources :orders do
    member do
      get :activate
    end
  end
  
  resources :donations do
    member do
      put :advance
    end
  end
  
  resources :answers
  
  resources :questions do
    resources :answers
  end
  
  resources :rewards do
    resources :donations
  end
  
  resources :fundings do
    resources :questions
    resources :rewards
    resources :donations do
      member do
        put :new
      end
    end
    
    member do
      put :publish
    end
  end
  
  controller :statistics do
    get 'statistics/index' => :index
    get 'statistics/current_requests' => :current_requests
  end
  
  resources :prefs do
    collection do
      get :overview
    end
    
    member do
      put :switch
    end
  end
  
  resources :votes
  
  resources :comments
  
  resources :arguments
  
  resources :proposals do
    resources :comments
    
    member do
      put :vote
    end
  end
  
  resources :decisions do
    resources :proposals
    
    member do
      put :publish
      put :vote
      get :result
    end
  end
  
  resources :messages
  
  resources :memberships do
    member do
      patch :accept
      get :activate
      get :show_summary
      get :requestpdf
    end
      
    collection do
      get :export
    end
  end
  
  resources :registrations do
    member do
      get :activate
    end
  end
  
  resources :pages do
    member do
      put :switchlock
    end
  end
  
  resources :contentparts do
    member do
      put :up
      put :to_top
      put :down
      put :to_bottom
    end
  end
  
  resources :newsletters do
    member do
      put :ready
      post :test
    end
  end
  
  resources :articles do
    member do
      put :publish
    end
  end
  
  resources :events do
    resources :registrations
  end
  
  resources :contacts do
    collection do
      get :email_address
    end
    
    member do
      get :activate
      get :unsubscribe
    end
    
    resources :messages
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    delete 'logout' => :destroy
  end
  
  resources :accounts do
    collection do
      match :build, via: %i( get patch )
      match :check, via: [ :get, :post ]
      match :request_password, via: [ :get, :post ]
      get :mine
    end
    member do
      match :reset_password, via: [ :get, :patch ]
    end
  end
  
  # Admin namespace
  
  namespace :admin do
    resources :accounts do
      member do
        patch :charm
      end
    end
    
    resources :memberships do
      resources :shares
      resources :payments
    end
    
    resources :shares do
      member do
        put :allocate
      end
    end
    
    resources :payments
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/search', to: 'application#search'
  get '/impressum', to: 'pages#impressum'
  get '/datenschutz', to: 'pages#datenschutz'
  
  # catch all route for database pages
  get '/*path', to: 'pages#show',
      constraints: lambda { |req|
          req.path.exclude? 'rails/active_storage' }
  
  root to: 'pages#root'
  
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  require 'prawn'
  
  skip_before_action :require_team
  before_action :require_admin, except: %i{ activate show_summary requestpdf show new create edit update }
  
  before_action :check_feature_enabled
  before_action :set_membership, only: %i{ accept activate show_summary requestpdf show edit update destroy }
  
  # --- CUSTOM METHODS -------------------------
  
  # PATCH /memberships/1/accept
  def accept
    @membership.update params.require( :membership ).permit( :starts_at )
    @membership.status = 'accepted'
    
    if @membership.save
      MembershipsMailer.with( membership: @membership ).
            membership_accepted.
            deliver_later if params[ :notify ] == 'yes'
      redirect_to @membership
      
    else
      redirect_to edit_membership_path( @membership ), alert: 'Du musst den Antrag erst korrekt ausfüllen und speichern'
    end
    
    write_log 'accept_membership', nil, @membership
  end
  
  # GET /memberships/1/activate
  def activate
    @successful = false
    
    if @membership.secret == params[ :ring ]
      @membership.status = 'confirmed'
      @membership.contact.status = 'confirmed'
      @membership.starts_at = Time.zone.now
      
      @successful = @membership.contact.save and @membership.save
    end
    
    write_log 'activate_membership', nil, @membership
  end
  
  # GET /memberships/1
  def show_summary
    require_admin_or_owner
  end
  
  # GET /membership/1/requestpdf
  def requestpdf
    membership_doc = make_membership_doc
    
    logger.debug "-- Rails.root: #{Rails.root}"
    to_add_page = CombinePDF.parse( membership_doc ).pages[ 0 ]
    
    template_pdf = CombinePDF.load Rails.root + 'app/assets/images/docs/mitgliedsantrag_blanko.pdf'
    template_pdf.pages.each { |page|
        page << to_add_page }
    
    send_data template_pdf.to_pdf, filename: "mitgliedsantrag_#{@membership.contact.name_text.underscore}.pdf", type: 'application/pdf', disposition: 'inline'
    
    write_log 'requestpdf_membership', nil, @membership
  end
  
  # GET /memberships/export
  def export_v1
    @memberships = Membership.includes :contact, :shares
    
    csv_groups = [ [ '', %w( token status ) ],
        [ 'contact', %w( last_name first_name custodian email ) ],
        [ '', %w( phone_nr gender birth_on street housenr plz city starts_at ends_at ) ],
        [ 'shares.first', %w( count amount ordered_at ) ],
        [ 'contact', %w( remarks ) ]
    ]
    csv_content = csv_groups.
        collect { |g|
            g.last }.
        flatten.
        join "\t"
    csv_content += "\r\n"
    csv_content += @memberships.
        collect { |m|
            csv_groups.
                collect { |g|
                    g.last.collect { |c|
                        g.first.blank? ?
                            m.send( c ) :
                            m.send( g.first ).
                                send( c )
                        }
                    }.
                flatten.
                join "\t" }.
        join "\r\n"
    
    send_data csv_content, filename: "mitglieder_stand_#{Time.zone.now.strftime "%Y%m%d_%H%M"}.tsv", type: :text
  end
  
  def export
    @memberships = Membership.find_by_sql "
        SELECT m.token AS token,
          m.status AS status,
          c.last_name AS last_name,
          c.first_name AS first_name,
          c.custodian AS custodian,
          c.email AS email,
          m.phone_nr AS phone_nr,
          m.gender AS gender,
          m.birth_on AS birth_on,
          m.street AS street,
          m.housenr AS housenr,
          m.plz AS plz,
          m.city AS city,
          m.starts_at AS starts_at,
          m.ends_at AS ends_at,
          s.count AS count,
          s.amount * s.count AS sum_amount,
          p.amount AS payment,
          p.paid_at AS paid_at,
          c.remarks AS remarks
        FROM memberships AS m
          LEFT JOIN contacts AS c ON m.contact_id=c.id
          LEFT JOIN shares AS s ON s.membership_id=m.id
          LEFT JOIN payments AS p ON p.membership_id=m.id
        ORDER BY last_name"
    
    column_titles = %w( token status last_name first_name email phone_nr gender birth_on street housenr plz city starts_at ends_at count sum_amount payment paid_at remarks )
    csv_content = column_titles.
        join( "\t" ) + "\r\n"
    csv_content += @memberships.
        collect { |m|
            column_titles.collect { |c|
                m.send( c ).to_s.
                    gsub( "\r\n", "; " ) }.
            join "\t" }.
        join "\r\n"
    
    send_data csv_content, filename: "mitglieder_stand_#{Time.zone.now.strftime "%Y%m%d_%H%M"}.tsv", type: :text
  end
  
  # --- STANDARD CRUD METHODS ------------------
  
  # GET /memberships
  # GET /memberships.json
  def index
    @letter_selected = params[ :letter ]
    @letters = Membership.find_by_sql "
        select left( c.last_name, 1 ) as letter
          from memberships as m
            left join contacts as c
            on m.contact_id = c.id
          group by letter
          order by letter asc"
    
    @dates_list = @letter_selected.to_s.length > 1
    @mem_count = Membership.count
    
    case params[ :letter ]
      when 'preliminary', 'completed', 'confirmed', 'status_new', 'accepted', 'cancelled', 'ended'
        @memberships = Membership.
            send( params[ :letter ] ).
            order 'memberships.created_at DESC'
      when 'with_saldo'
        @memberships = Membership.
            send( params[ :letter ] ).
            sort { |a,b| b.created_at <=> a.created_at }
      else
        @memberships = Membership.find_by_sql [ "
            select m.*
              from memberships as m
                left join contacts as c
                on m.contact_id = c.id
              where left( c.last_name, 1 ) = ?
              order by c.last_name", @letter_selected ]
    end
    
    write_log 'index_membership', nil, @membership
  end
  
  # GET /memberships/1
  # GET /memberships/1.json
  def show
    require_admin_or_owner
    
    if h_is_admin?
      render :show
    else
      render :show_member
    end
    
    write_log 'show_membership', nil, @membership
  end
  
  # GET /memberships/new
  def new
    redirect_to current_account.membership and return if h_is_member?
    
    if current_account and !h_is_admin?
      # if not already member, prefill contact
      contact = current_account.contact
      
    else
      contact = Contact.new( wants_news: true )
      contact.seed_checker_question
    end
    
    @membership = Membership.new( step: 1, contact: contact )
    write_log 'new_membership'
  end
  
  # GET /memberships/1/edit
  def edit
    require_admin_or_owner
    
    if h_is_admin?
      render :edit_admin
      
    else
      # ensure membership has contact
      unless @membership.contact
        if current_account
          @membership.contact = current_account.contact
        else
          @membership.build_contact
          @membership.contact.seed_checker_question
        end
      end
      @membership.contact.seed_checker_question
      
      # ensure there is a share when allowed
      if Pref.app_value( :allow_shares ) and @membership.shares.blank?
        @membership.shares.build( { count: 10, amount: Pref.app_value( :share_price ).to_f } )
      end
      
      # increase membership step
      @membership.step += 1
    end
    
    write_log 'edit_membership', nil, @membership
  end
  
  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new( membership_params )
    unless h_is_admin?
      @membership.status = 'preliminary'
    else
      @membership.status = 'new'
    end
    
    if current_account and
          current_account.contact and
          current_account.contact.email == @membership.contact.email
      @membership.contact = current_account.contact
    else
      @membership.contact.status = 'membership'
    end
    
    if h_is_team_or_member?
      # seed and solve, because we trust
      @membership.contact.op_a = @membership.contact.op_b = 1
      @membership.contact.solved = 2
    end
    
    respond_to do |format|
      if @membership.save
        session[ :membership_token ] = @membership.token
        
        format.html do
          if h_is_admin?
            redirect_to @membership
          else
            redirect_to edit_membership_path( @membership )
          end
        end
        format.json { render :show, status: :created, location: @membership }
        
      else
        # re-seed checker question
        if h_is_team_or_member?
          @membership.contact.op_a = @membership.contact.op_b = 1
          @membership.contact.solved = 2
        else
          @membership.contact.seed_checker_question
        end
        
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
    
    write_log 'create_membership', nil, @membership
  end
  
  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    @membership.update membership_params
    
    membership_done = @membership.step >= 5
    redirect_target = ( membership_done or h_is_admin? ) ? @membership : edit_membership_path( @membership )
    
    if @membership.contact and @membership.contact.new_record?
      @membership.contact.status = 'membership'
    end
    
    respond_to do |format|
      if @membership.save
        if membership_done
          @membership.update_attribute( :status, 'new' ) unless h_is_admin?
          
          if session[ :membership_token ] == @membership.token
            #MembershipsMailer.with( membership: @membership ).
            #confirmation_mail.
            #deliver_later
          end
        end
        
        format.html { redirect_to redirect_target }
        format.json { render :show, status: :ok, location: @order }
        
      else

app/helpers/memberships_helper.rb
module MembershipsHelper
  
  def h_fee_mode_class
    @membership.fee_mode != 'direct_debit' ? 'initially_hidden' : nil
  end
  
  def h_max_steps
    h_app_feature?( :allow_shares ) ? 5 : 4
  end
  
  def h_actor_for( in_membership, in_action )
    logs = @membership.logs.where( action: in_action )
    log = logs.last if in_action.include? 'create'
    log = logs.first if in_action.include? 'update' or in_action.include? 'accept'
    return '' unless log
    return "von #{log.actor.name_text}"
  end
  
end

app/views/memberships/_fields_membership_fees.html.haml
%fieldset
  %legend Mitgliedsbeitrag
    - unless h_is_admin?
      .help
        Die
        = h_orga_name
        erhebt Mitgliedsbeiträge in freiwilliger Höhe. Ziel ist ein Beitrag von 0,5% des jeweiligen Einkommens. Es bestimmt jedoch jedes Mitglied selbst, ob er/sie sich danach richten möchte.
        = link_to 'Mehr Infos'.html_safe, '#', data: { action: 'show_hide', sel: '#fee_help' }
      
      .help#fee_help.initially_hidden
        Die Beiträge werden im Voraus je Zahlungszeitraum erhoben. Beitragshöhe, Zahlungsweise und Zahlungsfrequenz lassen sich zu jedem Zahlungszeitraumsanfang auf Antrag ändern.
      
    
  
  .field
    = f.label :fee_amount
    = f.text_field :fee_amount
  
  .field
    = f.label :fee_period
    = f.select :fee_period, Membership.t_period_select
  
  .field
    = f.label :fee_mode
    = f.select :fee_mode, Membership.t_mode_select, {}, data: { sel: '#fee_mode_sepa' }
  
  #fee_mode_sepa{ class: h_fee_mode_class, data: { action: 'select_shows', which: '#membership_fee_mode', values: 'direct_debit' } }
    .field
    = f.label :account_owner
    = f.text_field :account_owner
    
    .field
    = f.label :iban
    = f.text_field :iban
    
    .field
      = f.check_box :accepts_debit
      = f.label :accepts_debit do
        Ich ermächtige
        = h_orga_name
        hiermit, den Mitgliedsbeitrag von meinem Konto mittels Lastschrift einzuziehen.
        = link_to 'Mehr Infos'.html_safe, '#', data: { action: 'show_hide', sel: '#sepa_help' }
      - unless h_is_admin?
        .help#sepa_help.initially_hidden
          Der Mitgliedsbeitrag wird regelmäßig mittels SEPA-Lastschrift von meinem Konto eingezogen. Ich kann innerhalb von acht Wochen, beginnend mit dem Belastungsdatum, die Erstattung des belasteten Betrages verlangen. Es gelten dabei die mit meinem Kreditinstitut vereinbarten Bedingungen. Das Mandat gilt für eine wiederkehrende Zahlung. Die Mandatsreferenz wird separat mitgeteilt.
          Gläubiger-Identifikationsnummer IBAN (Organisation, Adresse)
        
      
    
  
  - if h_is_admin?
    .field
      = f.label :fee_check_at
      = f.date_select :fee_check_at, include_blank: true
    
  

app/views/memberships/_form_accept.html.haml
- cancel_action = nil unless defined? cancel_action

= form_for membership, url: accept_membership_path( membership ) do |f|
  - if membership.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.membership.one" ), count: membership.errors.count )
      %ul
        - membership.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.membership.#{message.first}" )
        
      
    
  
  .field
    = f.label :starts_at
    = f.date_select :starts_at, start_year: 2020, end_year: ( Time.zone.now + 1.year ).year
  
  .field
    = check_box_tag 'notify', 'yes', false
    = label_tag :notiy, 'E-Mail Benachrichtigung senden?'
  
  .actions
    = cancel_action
    = f.submit class: 'button main'
  

app/views/memberships/_form_new_ex_2.html.haml
= form_for @membership do |f|
  - if @membership.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.membership.one" ), count: @membership.errors.count )
      %ul
        - @membership.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.membership.#{message.first}" )
        
      
    
  
  = f.hidden_field :step
  
  .row
    .field.big_part
      = f.label :street
      = f.text_field :street
    
    .field
      = f.label :housenr
      = f.text_field :housenr
    
  
  .row
    .field
      = f.label :plz
      = f.text_field :plz
    
    .field.big_part
      = f.label :city
      = f.text_field :city
    
  
  .field
    = f.label :phone_nr
    = f.text_field :phone_nr
  
  .actions
    = link_to 'Zurück', membership_path( @membership, membership: { step: @membership.step - 2 } ), method: :put, class: 'button secondary'
        
    = f.submit "Weiter…"
  

app/views/memberships/_form_new_ex_4.html.haml
= form_for @membership do |f|
  - if @membership.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.membership.one" ), count: @membership.errors.count )
      %ul
        - @membership.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.membership.#{message.first}" )
        
      
    
  
  = f.hidden_field :step
  
  %fieldset
    %legend Aufnahme
    .field
      = f.check_box :accepts_rules
      = f.label :accepts_rules do
        Hiermit stimme ich dem
        = link_to 'Grundkonsens von ' + h_orga_name, '/grundkonsens'
        zu und richte mein die Organisation betreffendes Handeln nach diesem aus.
      
    
    .field
      = f.check_box :wants_membership
      = f.label :wants_membership do
        Hiermit werde ich Mitglied von
        = h_orga_name + '.'
        Ich bin damit einverstanden, dass meine personenbezogenen Daten unter Beachtung der DSGVO (Verordnung EU 2016/679) gespeichert und innerhalb der Organisation verarbeitet werden. Eine Weitergabe an Dritte zu anderen Zwecken wird ausgeschlossen. Ich stimme zu, dass mein Vorname, Nachname, sowie die angegebene E-Mail-Adresse intern an Mitglieder zum Aufbauen von lokalen Kontakten weitergegeben wird. Als Mitglied erhalte ich automatisch den Newsletter der Organisation. Eine Abmeldung davon ist jederzeit möglich.
      
    
    - if h_app_feature? :membership_recommenders
      .field
        = f.label :recommendation
        = f.text_field :recommendation
        .help
          Welche Menschen aus der
          = h_orga_name
          würden dich evtl. für eine Mitgliedschaft empfehlen?
        
      
    
    - if h_app_feature? :other_memberships
      .field
        = f.label :other_memberships
        = f.text_area :other_memberships
        - unless h_is_admin?
          .help Bei welchen anderen Organisationen warst du oder bist du Mitglied?
        
      
    
  
  - if h_app_feature? :allow_membership_fees
    %fieldset
      %legend Mitgliedsbeitrag
      = render 'fields_membership_fees', f: f
    
  
  .actions
    = link_to 'Zurück', membership_path( @membership, membership: { step: @membership.step - 2 } ), method: :put, class: 'button secondary'
    - if h_app_feature? :allow_shares
      = f.submit "Weiter…"
    - else
      = f.submit "Sichern"
    
  

app/views/memberships/_form_new_ex_5.html.haml
= form_for @membership do |f|
  - if @membership.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.membership.one" ), count: @membership.errors.count )
      %ul
        - @membership.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.membership.#{message.first}" )
        
      
    
  
  = f.hidden_field :step
  
  = f.fields_for :shares, @membership.shares.first do |subf|
    = subf.hidden_field :membership_id
    = subf.hidden_field :amount
    
    %p
      Ein Anteil kostet
      = number_to_currency h_app_value( :share_price )
      
      - if h_app_feature? :membership_entry_fee
        %br
        Die Aufnahme als Mitglied kostet
        = number_to_currency h_app_value( :membership_entry_fee )
      
      - if h_app_feature? :share_buyers_fee
        %br
        Der Erwerb von Anteilen kostet
        = h_app_value( :share_buyers_fee )
        Prozent Verwaltungsgebühr
      
    
    .field
      .help Wie viele Anteile möchtest du zum Einstieg erwerben?
      = subf.label :count
      = subf.text_field :count, placeholder: 'empfohlen: min. 5'
    
    .summe
      Damit zahlst du insgesamt
      %span#sum_of_all= number_to_currency @membership.first_sum_of_all
    
  
  .actions
    = link_to 'Zurück', membership_path( @membership, membership: { step: @membership.step - 2 } ), method: :put, class: 'button secondary'
    = f.submit "Speichern"
  

app/views/memberships/_form_upload_request.html.haml
= form_for @membership do |f|
  - if @membership.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.membership.one" ), count: @membership.errors.count )
      %ul
        - @membership.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.membership.#{message.first}" )
        
      
    
  
  .field.file.image
    = f.label :request, 'Foto des unterschriebenen Antrags'
    = f.file_field :request
  
  .actions
    = f.submit 'Antrag hochladen', class: 'button'
  

app/views/memberships/_list.html.haml
%ul.memberships_list
  - the_date = Time.mktime( 1970, 1, 1 )
  - memberships.each do |membership|
    - if the_date != membership.sort_date and @dates_list
      - the_date = membership.sort_date
      %li.separator
        =l the_date, format: :short_day
      
    
    %li= render 'memberships/preview', membership: membership
  

app/views/memberships/activate.html.haml
%h1= @successful ? 'Danke' : 'Problem'

- if @successful
  %p
    Deine Bestätigung
    %strong war erfolgreich.
  
  %p
    Hier können wir mitteilen, was die nächsten Schritte sind... (tbd)
  
- else
  %p
    Der Link ist leider
    %strong nicht korrekt.
    %br
    Versuche bitte die Bestätigung nochmals.
  

app/views/memberships/create.html.haml
%h1 Mitgliedsantrag eingegangen

%p
  Prima, das hat soweit geklappt.
  %br
  Wir haben Deinen Mitgliedsantrag bekommen für:

%h3 Deine Kontaktdaten
%p
  %strong= @membership.contact.name_text
  %br
  %strong= @membership.street_nr_text
  %br
  %strong= @membership.plz_city_text

%p
  E-Mail:
  %strong= @membership.contact.email

- if @membership.other_memberships and h_app_feature? :other_memberships
  %p
    Folgende andere Mitgliedschaften hast du angegeben:
    %strong= @membership.other_memberships
  

- if h_app_feature? :allow_membership_fees
  %h3 Mitgliedsbeitrag
  %p
    Du hast folgenden Mitgliedsbeitrag gewählt:
    %strong
      = number_to_currency @membership.fee_amount
      = Membership.human_attribute_name "fee_period.#{@membership.fee_period}"
      via
      = Membership.human_attribute_name "fee_mode.#{@membership.fee_mode}"
    - if @membership.fee_mode == 'direct_debit'
      %br
      Kontoinhaber:in ist
      %strong= @membership.account_owner
      %br
      IBAN
      %strong= @membership.iban
    
  

%h3 Aufnahme
%p
  Empfohlen haben dich:
  %strong= @membership.recommendation
  - unless @membership.phone_nr.blank?
    %br
    Sprechen können wir dich unter
    %strong= @membership.phone_nr
  

%p
  Du hast dem Grundkonsens zugestimmt und möchtest Mitglied werden. Dazu stimmst du der Datenspeicherung zu.

%h3
  Vielen Dank und herzlich willkommen

%p
  Wir melden uns bei dir, wie es mit deinem Antrag weitergeht.
  %br
  Kennst Du Leute, die Du uns empfehlen könntest?
  %br
  Dann empfehle uns weiter, vielen Dank!

app/views/memberships/new_admin.html.haml
%h1 Neue Mitgliedschaft

= render 'form_admin'

app/views/memberships/not_enabled.html.haml
%h1 Sorry...
%p
  Mitgliedschaften sind bei uns
  %strong im Augenblick nicht möglich.

%p
  Du kannst aber gerne unseren
  = link_to 'Newsletter abonnieren', new_contact_path
  und bekommst dann Bescheid, wenn wir Mitgliedschaften anbieten.

app/views/memberships/show_member.html.haml
.membership_page
  .membership_member_process
    .status{ class: @membership.status_text }
      = @membership.status_text
    
    - if @membership.accepted? or @membership.member?
      %h1.membership_token
        Meine Mitgliedschaft
        .subtitle
          Mitgliedsnummer:
          = @membership.token
        
      
    - else
      %h1
        Mein Mitgliedsantrag
        .subtitle
          vorgesehene Mitgliedsnummer:
          = @membership.token
        
      
    
    %p
      - if @membership.starts_at
        - if @membership.member?
          Mitglied seit:
        - elsif @membership.accepted?
          Angenommen seit:
        
        %strong= l @membership.starts_at, format: :short_day
        
      - else
        Antrag gestellt am:
        %strong= l @membership.created_at, format: :short_day
      
      - if @membership.ends_at
        %br
        Beendet am:
        %strong= l @membership.ends_at, format: :short_day
      
    
    %h2
      %em Schritt 1:
      Herunterladen & Unterschreiben
      = '✅' if @membership.has_request?
    
    %p
      Dein Antrag ist digital eingegangen.
      %br
      Bitte lade ihn herunter, drucke ihn aus und unterschreibe ihn handschriftlich.
    
    .action_buttons
      .button_block
        = link_to 'Herunterladen', requestpdf_membership_path( @membership ), class: 'button', target: '_blank'
      
    
    %hr
    %h2
      %em Schritt 2:
      Fotografieren & hochladen
      = '✅' if @membership.has_request?
    
    - if @membership.has_request?
      %p
        Du hast deinen unterschriebenen Antrag hochgeladen.
      
      = render 'request_preview'
      
    - else
      %p
        Wenn du deinen Antrag unterschrieben hast, mache ein Foto und lade dieses hier wieder hoch.
      
      = render 'form_upload_request'
    
  