config/routes.rb
Rails.application.routes.draw do
  
  controller :community do
    get 'community', to: 'community#index'
    post 'community/search', to: 'community#search'
    get 'community/last_week', to: 'community#last_week', as: :last_week_community
    get 'community/:plz', to: 'community#show', as: :show_community
  end
  
  resources :taggings
  
  resources :tags do
    member do
      put :add
      put :orphanize
    end
  end
  
  resources :posts
  
  resources :participations do
    member do
      get :activate
    end
  end
  
  resources :streams do
    resources :participations
    resources :posts
  end
  
  resources :orderquants
  
  resources :orders do
    member do
      get :activate
    end
  end
  
  resources :donations do
    member do
      put :advance
    end
  end
  
  resources :answers
  
  resources :questions do
    resources :answers
  end
  
  resources :rewards do
    resources :donations
  end
  
  resources :fundings do
    resources :questions
    resources :rewards
    resources :donations do
      member do
        put :new
      end
    end
    
    member do
      put :publish
    end
  end
  
  controller :statistics do
    get 'statistics/index' => :index
    get 'statistics/current_requests' => :current_requests
  end
  
  resources :prefs do
    collection do
      get :overview
    end
    
    member do
      put :switch
    end
  end
  
  resources :votes
  
  resources :comments
  
  resources :arguments
  
  resources :proposals do
    resources :comments
    
    member do
      put :vote
    end
  end
  
  resources :decisions do
    resources :proposals
    
    member do
      put :publish
      put :vote
      get :result
    end
  end
  
  resources :messages
  
  resources :memberships do
    member do
      patch :accept
      get :activate
      get :show_summary
      get :requestpdf
    end
      
    collection do
      get :export
    end
  end
  
  resources :registrations do
    member do
      get :activate
    end
  end
  
  resources :pages do
    member do
      put :switchlock
    end
  end
  
  resources :contentparts do
    member do
      put :up
      put :to_top
      put :down
      put :to_bottom
    end
  end
  
  resources :newsletters do
    member do
      put :ready
      post :test
    end
  end
  
  resources :articles do
    member do
      put :publish
    end
  end
  
  resources :events do
    resources :registrations
  end
  
  resources :contacts do
    collection do
      get :email_address
    end
    
    member do
      get :activate
      get :unsubscribe
    end
    
    resources :messages
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    delete 'logout' => :destroy
  end
  
  resources :accounts do
    collection do
      match :build, via: %i( get patch )
      match :check, via: [ :get, :post ]
      match :request_password, via: [ :get, :post ]
      get :mine
    end
    member do
      match :reset_password, via: [ :get, :patch ]
    end
  end
  
  # Admin namespace
  
  namespace :admin do
    resources :accounts do
      member do
        patch :charm
      end
    end
    
    resources :memberships do
      resources :shares
      resources :payments
    end
    
    resources :shares do
      member do
        put :allocate
      end
    end
    
    resources :payments
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/search', to: 'application#search'
  get '/impressum', to: 'pages#impressum'
  get '/datenschutz', to: 'pages#datenschutz'
  
  # catch all route for database pages
  get '/*path', to: 'pages#show',
      constraints: lambda { |req|
          req.path.exclude? 'rails/active_storage' }
  
  root to: 'pages#root'
  
end

app/controllers/community_controller.rb
class CommunityController < ApplicationController
  skip_before_action :require_team, only: %i( search last_week index show )
  before_action :require_user, only: %i( last_week )
  
  # --- CUSTOM METHODS ------------------------
  
  def search
    @plz = params[ :query ] || '10000'
    
    @near_accounts = Contact.
        includes( :account ).
        where( 'LENGTH( plz ) > 0 AND
            FLOOR( plz / 1000 )= ?',
                @plz[ 0..1 ].to_i ).
        select { |c|
            c.account and
                c.account != current_account }.
        collect { |c| c.account }
    
    @other_accounts = Contact.
        includes( :account ).
        where( 'LENGTH( plz ) > 0 AND
            FLOOR( plz / 10000 )= ?',
                @plz[ 0 ].to_i ).
        select { |c|
            c.account and
                c.account != current_account and
                !@near_accounts.include? c }.
        collect { |c| c.account }
    
    write_log 'search_community', params[ :query ]
  end
  
  # GET /community/last_week
  def last_week
    @accounts = Account.new_last_week
    
    write_log 'last_week_community'
  end
  
  # --- STANDARD CRUD METHODS -----------------
  
  def index
    @new_accounts = Account.new_last_week
    
    write_log 'index_community'
  end
  
  def show
    @plz = params[ :plz ]
    if params[ :circle ] == 'near'
      @description = 'deiner Umgebung'
      @accounts = Contact.
          includes( :account ).
          where( 'LENGTH( plz ) > 0 AND
              FLOOR( plz / 1000 )= ?',
                  @plz[ 0..1 ].to_i ).
          select { |c|
              c.account and
                  c.account != current_account }.
        collect { |c| c.account }
      
    else
      @description = 'anderen Orten'
      @accounts = Contact.
          includes( :account ).
          where( 'LENGTH( plz ) > 0 AND
              FLOOR( plz / 10000 )= ?',
                  @plz[ 0 ].to_i ).
          select { |c|
              c.account and
                  c.account != current_account }.
        collect { |c| c.account }
    end
    
    write_log 'show_community', @plz
  end
  
end

app/helpers/community_helper.rb
module CommunityHelper
  
  def h_show_avatars?( in_accounts )
    h_avatar_accounts( in_accounts ).count > 0
  end
  
  def h_accounts_names( in_accounts )
    if h_show_avatars?( in_accounts )
      h_avatar_accounts( in_accounts ).
          collect { |a|
              a.displayname_text.
                  split( ' ' ).
                  first }.
                  join ', '
      
    elsif in_accounts.count > 0
      in_accounts[ 0..2 ].
          collect { |a|
              a.displayname_text.
                  split( ' ' ).
                  first }.
                  join ', '
    else
      'Niemand'
    end
  end
  
  def h_additional_count( in_accounts )
    in_accounts.count - h_accounts_names( in_accounts ).split( ', ' ).count
  end
  
  def h_avatar_accounts( in_accounts )
    in_accounts.
        select { |a|
            a.has_picture? }[ 0..2 ]
  end
  
  def h_save_plz?
    current_account and
        current_account.contact.plz.blank?
  end
  
end

app/views/community/_account_tile.html.haml
= link_to account, class: "account_tile" do
  .pic_n_name
    = render 'general/picture_thumb', entity: account
    .text
      .title= account.displayname_text
      .label= account.label
    
  
  - if account.description
    .description
      = truncate account.description, length: 100
    
  
  .link Profil ansehen &rsaquo;

app/views/community/_accounts_tile.html.haml
- description = 'in deiner Umgebung' unless defined?( description ) and !description.blank?
- link = community_search_path unless defined?( link ) and !link.blank?

= link_to link, class: "accounts_tile#{accounts.count > 0 ? '' : ' empty'}" do
  .content
    - if h_show_avatars?( accounts )
      .avatars
        - h_avatar_accounts( accounts ).each_with_index do |account,i|
          .picture.thumb{ style: "left: #{i*3}rem;" }= image_tag( ( account.picture_broken? ? 'sym/image_broken_w100.svg' : account.picture_thumb ), class: ( account.picture_broken? ? 'icon broken' : '' ) )
        
      
    
    .title= h_accounts_names( accounts )
    .description
      - if h_additional_count( accounts ) > 0
        und
        %strong
          = h_additional_count( accounts )
          weitere
        
      
      = description
    
  
  .arrow= image_tag 'sym/angle_right_s25.svg'

app/views/community/_community_details.html.haml
.last_week_block
  %h3 Neue Mitglieder letzte Woche
  = render 'accounts_tile', accounts: @new_accounts, link: last_week_community_path, description: 'in der letzten Woche'
  

app/views/community/_form_search.html.haml
= form_with url: community_search_path, local: true do |f|
  .field
    = f.label :query, 'Deine PLZ'
    = f.text_field :query, placeholder: 'z.B. 04321'
  
  .actions
    = f.submit 'Suche in der Nähe'
  

app/views/community/index.html.haml
%article.community_index
  %h1
    = Account.count
    Mitglieder in der Gemeinschaft
  
  - if current_account
    = render 'community_details'
  
  .search_block
    %h3 Suche nach Mitgliedern
    %p
      Du suchst Gruppen in deiner Nähe?
      %br
      Oder einfach andere Interessierte für einen netten Austausch?
    
    = render 'form_search'
  

app/views/community/last_week.html.haml
%article.community_show
  %h1
    = @accounts.count
    neue Mitglieder in der letzten Woche
  
  %ul.account_tile_list
    - @accounts.each do |account|
      %li
        = render 'account_tile', account: account
      
    
  

app/views/community/search.html.haml
%article.community_search
  - if h_save_plz?
    .save_plz
      %h3 Ist das deine Postleitzahl?
      %p
        Andere wollen dich vielleicht
        %strong auch finden.
        Du hast aber noch keine PLZ hinterlegt.
      
      %p
        Dürfen wir
        %strong diese PLZ für dich speichern?
      
      = render 'contacts/form_plz_community', contact: current_account.contact, redirect: community_path
    
  
  %h1 Mitglieder in deiner Nähe
  = render 'accounts_tile', accounts: @near_accounts, link: show_community_path( plz: @plz, circle: 'near' )
  
  %h2 Mitglieder in anderen Orten
  = render 'accounts_tile', accounts: @other_accounts, description: ' an anderen Orten', link: show_community_path( plz: @plz, circle: 'far' )

app/views/community/show.html.haml
%article.community_show
  %h1
    Mitglieder in
    = @description
  
  %ul.account_tile_list
    - @accounts.each do |account|
      %li
        = render 'account_tile', account: account
      
    
  