config/routes.rb
Rails.application.routes.draw do
  
  controller :community do
    get 'community', to: 'community#index'
    post 'community/search', to: 'community#search'
    get 'community/last_week', to: 'community#last_week', as: :last_week_community
    get 'community/:plz', to: 'community#show', as: :show_community
  end
  
  resources :taggings
  
  resources :tags do
    member do
      put :add
      put :orphanize
    end
  end
  
  resources :posts
  
  resources :participations do
    member do
      get :activate
    end
  end
  
  resources :streams do
    resources :participations
    resources :posts
  end
  
  resources :orderquants
  
  resources :orders do
    member do
      get :activate
    end
  end
  
  resources :donations do
    member do
      put :advance
    end
  end
  
  resources :answers
  
  resources :questions do
    resources :answers
  end
  
  resources :rewards do
    resources :donations
  end
  
  resources :fundings do
    resources :questions
    resources :rewards
    resources :donations do
      member do
        put :new
      end
    end
    
    member do
      put :publish
    end
  end
  
  controller :statistics do
    get 'statistics/index' => :index
    get 'statistics/current_requests' => :current_requests
  end
  
  resources :prefs do
    collection do
      get :overview
    end
    
    member do
      put :switch
    end
  end
  
  resources :votes
  
  resources :comments
  
  resources :arguments
  
  resources :proposals do
    resources :comments
    
    member do
      put :vote
    end
  end
  
  resources :decisions do
    resources :proposals
    
    member do
      put :publish
      put :vote
      get :result
    end
  end
  
  resources :messages
  
  resources :memberships do
    member do
      patch :accept
      get :activate
      get :show_summary
      get :requestpdf
    end
      
    collection do
      get :export
    end
  end
  
  resources :registrations do
    member do
      get :activate
    end
  end
  
  resources :pages do
    member do
      put :switchlock
    end
  end
  
  resources :contentparts do
    member do
      put :up
      put :to_top
      put :down
      put :to_bottom
    end
  end
  
  resources :newsletters do
    member do
      put :ready
      post :test
    end
  end
  
  resources :articles do
    member do
      put :publish
    end
  end
  
  resources :events do
    resources :registrations
  end
  
  resources :contacts do
    collection do
      get :email_address
    end
    
    member do
      get :activate
      get :unsubscribe
    end
    
    resources :messages
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    delete 'logout' => :destroy
  end
  
  resources :accounts do
    collection do
      match :build, via: %i( get patch )
      match :check, via: [ :get, :post ]
      match :request_password, via: [ :get, :post ]
      get :mine
    end
    member do
      match :reset_password, via: [ :get, :patch ]
    end
  end
  
  # Admin namespace
  
  namespace :admin do
    resources :accounts do
      member do
        patch :charm
      end
    end
    
    resources :memberships do
      resources :shares
      resources :payments
    end
    
    resources :shares do
      member do
        put :allocate
      end
    end
    
    resources :payments
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/search', to: 'application#search'
  get '/impressum', to: 'pages#impressum'
  get '/datenschutz', to: 'pages#datenschutz'
  
  # catch all route for database pages
  get '/*path', to: 'pages#show',
      constraints: lambda { |req|
          req.path.exclude? 'rails/active_storage' }
  
  root to: 'pages#root'
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  belongs_to :parent, class_name: 'Tag', optional: true
  has_many :children, foreign_key: :parent_id, class_name: 'Tag', dependent: :nullify
  has_many :taggings, dependent: :destroy
  
  # -------------------------------------------
  
  def preview_text
    label
  end
  
  def tagging_for( in_entity )
    taggings.detect { |t| t.entity == in_entity }
  end
  
  def entities
    taggings.collect { |t| t.entity }
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ orphanize show edit update destroy ]
  
  skip_before_action :require_team, only: %i[ quiz_categories ]
  
  # --- CUSTOM METHODS ------------------------
  
  # PUT /tags/1/add
  def add
    logger.debug "-- add @ tags controller"
    logger.debug params.to_yaml
  end
  
  # PUT /tags/1/orphanize
  def orphanize
    parent = @tag.parent
    
    if @tag.update_attribute 'parent', nil
      redirect_to parent, notice: 'Marke wurde erfolgreich entfernt.'
      write_log 'orphanize_tag', nil, @tag
      
    else
      redirect_to parent, alert: 'Marke konnte nicht entfernt werden.'
    end
  end
  
  # --- STANDARD CRUD METHODS -----------------
  
  # GET /tags
  # GET /tags.json
  def index
    redirect_to login_path, alert: 'Um diese Seite zu sehen, musst du bestimmte Zugriffsrechte haben.' and return unless h_is_editor? or h_app_value( :team_sees_tags )
    
    logger.debug "-- index @ tags controller"
    @tags = Tag.includes( :taggings ).order( 'kind ASC, label ASC' )
    
    write_log 'index_tags', current_account ? current_account.status : nil
  end
  
  # GET /tags/1
  # GET /tags/1.json
  def show
    write_log 'show_tag', nil, @tag
  end
  
  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new( tag_params )
    @tag.status = 'new'
    
    if params[ :entity_type ]
      # should the new tag be attached to an
      # entity given?
      @entity = params[ :entity_type ].to_s.classify.constantize.find params[ :entity_id ]
      @tag.taggings.build( entity_type: @entity.class, entity_id: @entity.id )
      redirect_target = @entity
    else
      # create a new sub tag to an existing tag
      redirect_target = @tag.parent
    end
    
    respond_to do |format|
      if @tag.save
        format.html { redirect_to redirect_target, notice: 'Marke wurde erfolgreich angelegt und angehängt.' }
        format.json { render :show, status: :created, location: @tag }
        
        write_log 'create_tag', nil, @tag
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    redirect_to login_path,
            notice: 'Bitte anmelden!' and return unless h_is_editor?
    
    respond_to do |format|
      if @tag.update( tag_params )
        if tag_params[ :parent_id ]
          format.html { redirect_to @tag.parent, notice: 'Marke wurde erfolgreich geändert.' }
        else
          format.html { redirect_to @tag, notice: 'Marke wurde erfolgreich geändert.' }
        end
        format.json { render :show, status: :ok, location: @tag }
        
        write_log 'create_tag', nil, @tag
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end
  
private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find params[ :id ]
    render_404 and return if @tag.blank?
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require( :tag ).permit( :label, :color, :parent_id )
  end
  
end

app/views/tags/_list_at_entity.html.haml
- editable = false unless defined? editable and editable == true
- logger.debug "-- editable: #{editable}"

- if entity.tags.count > 0 or editable
  %ul.tags_list_at_entity
    - entity.tags.each do |tag|
      - unless tag.new_record?
        %li.tag_display{ style: tag.color? ? "background-color: #{tag.color}" : nil }
          .label= tag.label
          - if editable
            = link_to image_tag( 'sym/cross_w100.svg' ), tag.tagging_for( entity ), method: :delete, class: 'delete_button'
        
      
    - if editable
      %li.tag_actions
        #add_tag_button.sym_button{ title: 'Marke anhängen' }
          = image_tag 'sym/tag_plus_w100.svg'
        
        = render 'tags/tagger_modal', entity: entity
      
    
  

app/views/tags/_list_children.html.haml
- link = false unless defined? link and link == true

%ul.tags_list_at_entity
  - tag.children.each do |tag|
    - unless tag.new_record?
      %li.tag_display{ style: tag.color? ? "background-color: #{tag.color}" : nil }
        = link_to tag do
          .label= tag.label
        
      
    
  

app/views/tags/_preview.html.haml
= link_to tag, class: 'tag_display', style: tag.color? ? "background-color: #{tag.color}" : nil do
  .label= tag.label

- unless tag.taggings.blank?
  .info_label
    = tag.taggings.count
    zugeordnete Elemente
  

- unless tag.children.blank?
  = render 'tags/list_children', tag: tag, link: true

app/views/tags/_tagger_modal.html.haml
#tagger_modal.tagger_modal
  .search_block
    .close_window_button= image_tag 'sym/cross_w100.svg'
    = text_field_tag 'label'
  
  .results_block
    %ul.tags_list_in_tagger
      - Tag.order( 'label ASC' ).all.each do |tag|
        %li{ data: { label: tag.label } }
          = button_to tag.label, taggings_path, params: { tagging: { tag_id: tag.id, entity_type: entity.class, entity_id: entity.id } }, style: tag.color? ? "background-color: #{tag.color}" : nil
        
      %li#create_new_tag_tagging_form{ data: { label: '' } }
        = button_to '', tags_path, params: { tag: { label: '' }, entity_type: entity.class, entity_id: entity.id }
      
      %li.help_text tippe, um Marken auszuwählen
    
  

app/views/tags/index.html.haml
- h_title 'Liste aller Marken'
- h_description( h_page_description_for 'tags' )

%h1 Liste aller Marken

%ul.tags_index
  - kind = ''
  - @tags.each do |tag|
    - if tag.kind != kind
      - kind = tag.kind
      %li.separator= kind
    
    %li
      = render 'preview', tag: tag
    
  

app/views/tags/show.html.haml
- h_page_title @tag.label
- h_description "Alle Sachen, die mit #{@tag.label} markiert sind."

%h1
  Marke
  .tag_display{ style: @tag.color? ? "background-color: #{@tag.color}" : nil }
    .label= @tag.label
  

.list_title untergeordnete Marken
%ul.tags_list_at_entity
  - @tag.children.each do |tag|
    - unless tag.new_record?
      %li.tag_display{ style: tag.color? ? "background-color: #{tag.color}" : nil }
        .label= tag.label
        - if h_is_editor?
          = link_to image_tag( 'sym/cross_w100.svg' ), orphanize_tag_path( tag ), method: :put, class: 'delete_button'
        
      
    
  - if h_is_editor?
    %li.tag_actions
      #add_tag_button.sym_button{ title: 'Marke anhängen' }
        = image_tag 'sym/tag_plus_w100.svg'
      
      #tagger_modal.tagger_modal
        .search_block
          .close_window_button= image_tag 'sym/cross_w100.svg'
          = text_field_tag 'label'
        
        .results_block
          %ul.tags_list_in_tagger
            - Tag.order( 'label ASC' ).all.each do |tag|
              %li{ data: { label: tag.label } }
                = button_to tag.label, tag_path( tag ), params: { tag: { parent_id: @tag.id } }, method: :patch, style: tag.color? ? "background-color: #{tag.color}" : nil
              
            %li#create_new_tag_tagging_form{ data: { label: '' } }
              = button_to '', tags_path, params: { tag: { label: '', parent_id: @tag.id } }
            
            %li.help_text tippe, um Marken auszuwählen
          
        
      
    
  

%ul.entity_list
  - @tag.entities.each do |entity|
    - entity_name = entity.class.to_s.parameterize
    %li
      = render "#{entity_name.pluralize}/preview_tag", "#{entity_name}": entity
    
  