config/routes.rb
Rails.application.routes.draw do
  
  controller :community do
    get 'community', to: 'community#index'
    post 'community/search', to: 'community#search'
    get 'community/last_week', to: 'community#last_week', as: :last_week_community
    get 'community/:plz', to: 'community#show', as: :show_community
  end
  
  resources :taggings
  
  resources :tags do
    member do
      put :add
      put :orphanize
    end
  end
  
  resources :posts
  
  resources :participations do
    member do
      get :activate
    end
  end
  
  resources :streams do
    resources :participations
    resources :posts
  end
  
  resources :orderquants
  
  resources :orders do
    member do
      get :activate
    end
  end
  
  resources :donations do
    member do
      put :advance
    end
  end
  
  resources :answers
  
  resources :questions do
    resources :answers
  end
  
  resources :rewards do
    resources :donations
  end
  
  resources :fundings do
    resources :questions
    resources :rewards
    resources :donations do
      member do
        put :new
      end
    end
    
    member do
      put :publish
    end
  end
  
  controller :statistics do
    get 'statistics/index' => :index
    get 'statistics/current_requests' => :current_requests
  end
  
  resources :prefs do
    collection do
      get :overview
    end
    
    member do
      put :switch
    end
  end
  
  resources :votes
  
  resources :comments
  
  resources :arguments
  
  resources :proposals do
    resources :comments
    
    member do
      put :vote
    end
  end
  
  resources :decisions do
    resources :proposals
    
    member do
      put :publish
      put :vote
      get :result
    end
  end
  
  resources :messages
  
  resources :memberships do
    member do
      patch :accept
      get :activate
      get :show_summary
      get :requestpdf
    end
      
    collection do
      get :export
    end
  end
  
  resources :registrations do
    member do
      get :activate
    end
  end
  
  resources :pages do
    member do
      put :switchlock
    end
  end
  
  resources :contentparts do
    member do
      put :up
      put :to_top
      put :down
      put :to_bottom
    end
  end
  
  resources :newsletters do
    member do
      put :ready
      post :test
    end
  end
  
  resources :articles do
    member do
      put :publish
    end
  end
  
  resources :events do
    resources :registrations
  end
  
  resources :contacts do
    collection do
      get :email_address
    end
    
    member do
      get :activate
      get :unsubscribe
    end
    
    resources :messages
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    delete 'logout' => :destroy
  end
  
  resources :accounts do
    collection do
      match :build, via: %i( get patch )
      match :check, via: [ :get, :post ]
      match :request_password, via: [ :get, :post ]
      get :mine
    end
    member do
      match :reset_password, via: [ :get, :patch ]
    end
  end
  
  # Admin namespace
  
  namespace :admin do
    resources :accounts do
      member do
        patch :charm
      end
    end
    
    resources :memberships do
      resources :shares
      resources :payments
    end
    
    resources :shares do
      member do
        put :allocate
      end
    end
    
    resources :payments
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/search', to: 'application#search'
  get '/impressum', to: 'pages#impressum'
  get '/datenschutz', to: 'pages#datenschutz'
  
  # catch all route for database pages
  get '/*path', to: 'pages#show',
      constraints: lambda { |req|
          req.path.exclude? 'rails/active_storage' }
  
  root to: 'pages#root'
  
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  include Tokenize
  after_initialize :fill_in_token
  
  include Publish
  after_initialize :set_publish_status
  
  belongs_to :account
  belongs_to :decision
  has_many :comments, as: :entity, dependent: :destroy
  has_many :votes, dependent: :destroy
  
  # --- VALIDATIONS ---------------------------
  
  validates_presence_of :title
  
  # --- SCOPES --------------------------------
  
  scope :published, -> {
        where status: 'published' }
  
  # --- PREDICATES ----------------------------
  
  def comments?
    comments.count > 0
  end
  
  # --- INSTANCE METHODS ----------------------
  
  def iid
    "pr_#{token}"
  end
  
  def to_param
    "#{token}"
  end
  
  def position
    index = decision.proposals.find_index { |p| p == self }
    return index + 1
  end
  
  def has_votes?
    votes.published.count > 0
  end
  
  def voters_published
    unless defined? @voters_published
      the_votes = votes.includes( :account ).all.references( :account)
      @voters_published = the_votes.select { |v|
          v.published? }.collect { |v|
          v.account }
    end
    return @voters_published
  end
  
  def votes_for( in_account )
    unless defined? @_votes
      @_votes = votes.includes( :account ).where( account: in_account ).references( :account )
    end
    return @_votes
  end
  
  def vote_for( in_account )
    votes_for( in_account ).first
  end
  
  def vote_value_for( in_account )
    vote = vote_for( in_account )
    return nil if vote.blank?
    return vote.value
  end
  
  def votes_value
    unless defined? @votes_value
      if voters_published.count < 1
        @votes_value = 0
        
      else
        value_sum = votes.published.inject(0) { |sum, v|
          sum + v.value }
        @votes_value = ( value_sum * 100.0 / voters_published.count ).round / 100.0
      end
    end
    return @votes_value
  end
  
  def selection_value
    unless defined? @selection_value
      unless has_votes? or decision.voters_published.count == 0
        @selection_value = 0
        
      else
        @selection_value = votes.published.inject(0) { |sum, v|
          sum + v.value }
      end
    end
    return @selection_value
  end
  
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [ :vote, :show, :edit, :update, :destroy ]
  before_action :set_decision, only: [ :create ]
  skip_before_action :require_team
  before_action :require_decider
  
  # --- CUSTOM METHODS -------------------------
  
  # PUT / proposal/1/vote.js
  def vote
    return unless current_account and current_account.can_vote_for? @proposal
    
    @vote = @proposal.votes.for_account( current_account ).first
    if @vote
      if is_same_value? or is_selection_and_zero?
        @vote.destroy
      else
        @vote.value = params[ :value ].to_i
      end
      
    else
      return unless params[ :value ].to_i >= 0
      return if too_many_selections?
      
      @vote = @proposal.votes.build( status: 'new', account: current_account, value: params[ :value ].to_i )
    end
    logger.debug "-- vote:#{@vote.to_yaml}"
    @vote.save unless @vote.frozen?
  end
  
  # GET /proposals
  # GET /proposals.json
  def index
    render_404
    #@proposals = Proposal.all
  end
  
  # GET /proposals/1
  # GET /proposals/1.json
  def show
    redirect_to @proposal.decision
  end
  
  # GET /proposals/new
  def new
    redirect_to decisions_path, alert: 'Vorschlag kann nur zu einer Entscheidung eingebracht werden' and return unless params[ :decision_id ]
    
    @decision = Decision.find_by token: params[ :decision_id ]
    @proposal = @decision.proposals.build
  end
  
  # GET /proposals/1/edit
  def edit
  end
  
  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = @decision.proposals.build( proposal_params )
    @proposal.status = 'published'
    @proposal.account = current_account
    
    respond_to do |format|
      if @proposal.save
        format.js { @decision.proposals.reload }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @decision = @proposal.decision
    @proposal.destroy
    
    respond_to do |format|
      format.html { redirect_to @decision, notice: 'Vorschlag wurde gelöscht.' }
      format.json { head :no_content }
    end
  end
  
private
  # Use callbacks to share common setup or constraints between actions.
  def set_proposal
    @proposal = Proposal.find_by token: params[ :id ]
    render_404 and return if @proposal.blank?
  end
  
  def set_decision
    @decision = Decision.find_by token: params[ :decision_id ]
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def proposal_params
    params.require( :proposal ).permit( :title, :description )
  end
  
  # --- PREDICATES -----------------------------
  
  def is_same_value?
    params[ :value ].to_i == @vote.value
  end
  
  def is_selection_and_zero?
    @proposal.decision.is_selection? and params[ :value ].to_i == 0
  end
  
  def too_many_selections?
    decision = @proposal.decision
    return ( decision.is_selection? and decision.vote_count_for( current_account ) >= decision.vote_count )
  end
  
end

app/helpers/proposals_helper.rb
module ProposalsHelper
  
  def h_vote_value_class( in_vote, in_value )
    klass = ''
    return klass if in_vote.blank?
    klass += " a#{(in_vote / 2.0).floor + 1 }" if in_vote >= in_value
    klass += ' hilite' if in_vote == in_value
    return klass
  end
  
  def h_result_value_class( in_proposal )
    vote = in_proposal.votes_value
    klass = ''
    klass += " a#{(vote / 2.0).floor + 1 }"
    return klass
  end
  
  def h_proposal_editable?( in_proposal )
    in_proposal.decision.proposing? and in_proposal.account == current_account
  end
  
  def h_show_toggler?( in_proposal )
    !in_proposal.description.blank? or h_proposal_editable?( in_proposal )
  end
  
end

app/views/proposals/_edit.html.haml
%li{ id: proposal.iid }
  .proposal_card
    = render 'proposals/form', proposal: proposal, cancel_action: link_to( 'Abbrechen', proposal.decision, class: 'button' ), delete_action: link_to( image_tag( 'sym/bin_w100.svg' ), proposal, method: :delete, class: 'sym_button danger', data: { confirm: "Willst du wirklich den Vorschlag '#{proposal.title}' löschen?\n\nDie Aktion kann nicht rückgängig gemacht werden." } )
  

app/views/proposals/_form.html.haml
= form_for @proposal do |f|
  - if @proposal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@proposal.errors.count, "error")} prohibited this proposal from being saved:"
      %ul
        - @proposal.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  .field
    = f.label :title
    .help
      Beschreibe deinen Vorschlag kurz, den du als Lösung der Frage einbringen möchtest.
      %br
      (max. 250 Zeichen)
    
    = f.text_area :title, rows: 3, maxlength: 250
  
  .field
    = f.label :description
    = f.text_area :description, rows: 5, placeholder: 'z.B. Details, die den Vorschlag erklären...'
  
  .actions
    .start_side= delete_action
    = cancel_action
    = f.submit 'Speichern'
  

app/views/proposals/_form_new.html.haml
= form_for [ @proposal.decision, @proposal ], remote: true do |f|
  - if @proposal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@proposal.errors.count, "error")} prohibited this proposal from being saved:"
      %ul
        - @proposal.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  .field
    = f.label :title
    .help
      Beschreibe deinen Vorschlag kurz, den du als Lösung der Frage einbringen möchtest.
      %br
      (max. 250 Zeichen)
    
    = f.text_area :title, rows: 3, maxlength: 250
  
  .field.initially_hidden#desc
    = f.label :description
    = f.text_area :description, rows: 5, placeholder: 'z.B. Details, die den Vorschlag erklären...'
    
  .actions
    .start_side
      .toggler_text{ data: { action: 'show_hide', sel: "#desc" } } Beschreibung dazu
    
    = cancel_action
    = f.submit 'Speichern'
  

app/views/proposals/_index.html.haml
- proposals = [] unless defined? proposals

- # --------------------------------------------

#proposals_list
  %header.list_title
    = proposals.count
    Vorschläge
  
  %ul.proposals_list
    - proposals.each do |proposal|
      - logger.debug "== next proposal in list -- proposal:#{proposal.token}"
      = render 'proposals/preview', proposal: proposal
    
  

app/views/proposals/_new.html.haml
.non_form#new_proposal
  = render 'form_new', cancel_action: link_to( 'Abbrechen', @proposal.decision, class: 'button' )

app/views/proposals/_preview.html.haml
- if defined?( is_open ).nil?
  - is_open = true

%li{ id: proposal.iid }
  .proposal_card
    .short_content.will_toggle{ class: is_open ? 'open' : nil, data: { action: 'toggle', sel: "##{proposal.iid} .full_content" } }
      .end_aligned= render 'general/toggle_icon'
      
      .title
        .number
          Vorschlag
          %strong= proposal.position
        
        = proposal.title
      
      = render 'comments/preview_count', entity: proposal
    
    .full_content.will_be_toggled{ class: is_open ? 'toggled_open' : nil }
      - unless proposal.description.blank?
        .description
          = h_format proposal.description
        
      
    - if proposal.decision.voting?
      - logger.debug "== start resistance_scale"
      = render 'proposals/resistance_scale', proposal: proposal
    - elsif proposal.decision.done?
      - if proposal.decision.is_selection?
        .selection_result
          = proposal.selection_value
        
      - else
        = render 'proposals/result_scale', proposal: proposal
      
    
    .full_content.will_be_toggled{ class: is_open ? 'toggled_open' : nil }
      - if proposal.decision.proposing?
        .actions
          - if h_proposal_editable?( proposal )
            = link_to image_tag( 'sym/pencil_w100.svg' ), edit_proposal_path( proposal ), remote: true, class: 'sym_button'
          
          - if proposal.decision.proposing?
            .sym_text_button.will_toggle{ data: { action: 'toggle', sel: "#new_comment_#{proposal.iid}" } }
              = image_tag 'sym/comment_w100.svg', class: 'sym_button'
              .label kommentieren
            
          
        
      
      .comments_block{ class: ( proposal.comments? ? nil : 'will_be_toggled' ), id: ( proposal.comments? ? nil : "new_comment_#{proposal.iid}" ) }
        - if proposal.comments?
          = render 'comments/list', entity: proposal, deletable: proposal.decision.proposing?
        
        - if proposal.decision.proposing?
          .comment_form{ class: proposal.comments? ? 'will_be_toggled' : nil, id: proposal.comments? ? "new_comment_#{proposal.iid}" : nil }
            - cancel_action = capture do
              .button{ data: { action: 'toggle', sel: "#new_comment_#{proposal.iid}" } } Abbrechen
            
            = render 'comments/form', comment: proposal.comments.build, cancel_action: cancel_action
          
        
      
    
  

app/views/proposals/_resistance_scale.html.haml
- votable = proposal.decision.votable_by? current_account
- vote = proposal.vote_value_for( current_account )

.voting_section
  - if votable or !vote.blank?
    - if proposal.decision.is_selection?
      .selection_scale
        
        .end_aligned
          .label
            - if vote == 1
              ausgewählt
            - else
              bisher enthalten
            
          
          = link_to image_tag( "sym/vote_circle_#{vote == 1 ? 'cross_' : '' }b100.svg" ), vote_proposal_path( proposal, value: 1 ), method: :put, remote: true, class: 'vote_circle'
      
    - else
      %ul.resistance_scale
        - ( 0..9 ).each do |value|
          - if votable
            %li
              = link_to value.to_s, vote_proposal_path( proposal, value: value ), method: :put, remote: true, class: "tick" + h_vote_value_class( vote, value )
            
          - else
            %li
              .tick.inactive{ class: h_vote_value_class( vote, value ) }= value
          
        
      
    
  
  .scale_labels
    - if votable or !vote.blank?
      - unless proposal.decision.is_selection?
        .left kein Widerstand
        .right hoher Widerstand
      
    
  

app/views/proposals/_result_scale.html.haml
.voting_section
  .result_scale{ class: h_result_value_class( proposal ), style: "width: #{proposal.votes_value * 11.11}%;" }
    &nbsp;
    
    .result_tick{ class: h_result_value_class( proposal ), style: "right: #{[(-3 + proposal.votes_value * 2),0].min}rem;" }
      = proposal.votes_value
    
  
  .scale_labels
    .left kein Widerstand
    .right hoher Widerstand
  

app/views/proposals/create.js.erb
$("#new_proposal").slideUp( 200 ).empty();
$("#new_proposal_button").slideDown( 200 );
$("#proposals_list").replaceWith( "<%= escape_javascript( render 'proposals/index', proposals: @decision.proposals ) %>" );

app/views/proposals/edit.js.erb
$("#<%= @proposal.iid %>").replaceWith( "<%= escape_javascript( render 'proposals/edit', proposal: @proposal ) %>" );

app/views/proposals/index.html.haml
%h1 Listing proposals

%table
  %thead
    %tr
      %th Token
      %th Status
      %th Account
      %th Decision
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @proposals.each do |proposal|
      %tr
        %td= proposal.token
        %td= proposal.status
        %td= proposal.account
        %td= proposal.decision
        %td= proposal.title
        %td= proposal.description
        %td= link_to 'Show', proposal
        %td= link_to 'Edit', edit_proposal_path(proposal)
        %td= link_to 'Destroy', proposal, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Proposal', new_proposal_path

app/views/proposals/new.html.haml
- cancel_action = capture do
  = link_to 'Abbrechen', proposals_path, class: 'button'


%h1 Neuer Vorschlag
%p
  Hier kannst du einen neuen Vorschlag für die Fragestellung
  %br
  %strong= @proposal.decision.title
  %br
  einbringen.

%p
  Beschreibe dazu präzise, was du zur Abstimmung vorschlägst.

= render 'form', cancel_action: cancel_action

app/views/proposals/new.js.erb
$("#new_proposal").replaceWith( "<%= escape_javascript( render 'new' ) %>" );
$("#new_proposal_button").slideUp( 200 );

app/views/proposals/vote.js.erb
proposal_li = $("#<%= @proposal.iid %>");
was_open = proposal_li.hasClass( 'open' );
proposal_li.replaceWith( "<%= escape_javascript( render 'proposals/preview', proposal: @proposal ) %>" );
if ( was_open ) {
  $("#<%= @proposal.iid %>").addClass( 'open' );
}